---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    driver:
      box: ubuntu/trusty64
  - name: ubuntu-12.04
  - name: debian/jessie64
    driver:
      box: debian/jessie64
  - name: debian-7.4
    driver:
      box: opscode-debian-7.4
  - name: centos-6.4

suites:
  - name: default
    run_list:
    - recipe[rubywebserv::install]
    attributes:
      apt:
        compile_time_update: true
